// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFakc8t9qBBGqBEwN0nu67s5kkdWgNHHU',
    appId: '1:721602485143:web:327d4886ef232ba89dc2d2',
    messagingSenderId: '721602485143',
    projectId: 'mynotes-learning-flut',
    authDomain: 'mynotes-learning-flut.firebaseapp.com',
    storageBucket: 'mynotes-learning-flut.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsxMbebusCDLsz4mJMh6rU6tD7I3Seq10',
    appId: '1:721602485143:android:69747c05f7b071349dc2d2',
    messagingSenderId: '721602485143',
    projectId: 'mynotes-learning-flut',
    storageBucket: 'mynotes-learning-flut.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_LYO7mC6o9jhPyx_viGMhkx_enHkMVC8',
    appId: '1:721602485143:ios:e94a8a8a6c2ae6909dc2d2',
    messagingSenderId: '721602485143',
    projectId: 'mynotes-learning-flut',
    storageBucket: 'mynotes-learning-flut.firebasestorage.app',
    iosBundleId: 'com.something.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_LYO7mC6o9jhPyx_viGMhkx_enHkMVC8',
    appId: '1:721602485143:ios:e94a8a8a6c2ae6909dc2d2',
    messagingSenderId: '721602485143',
    projectId: 'mynotes-learning-flut',
    storageBucket: 'mynotes-learning-flut.firebasestorage.app',
    iosBundleId: 'com.something.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFakc8t9qBBGqBEwN0nu67s5kkdWgNHHU',
    appId: '1:721602485143:web:432409400936d1139dc2d2',
    messagingSenderId: '721602485143',
    projectId: 'mynotes-learning-flut',
    authDomain: 'mynotes-learning-flut.firebaseapp.com',
    storageBucket: 'mynotes-learning-flut.firebasestorage.app',
  );
}
